In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define the vocabulory size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3318, 1828, 9294, 9976],
 [3318, 1828, 9294, 2642],
 [3318, 1219, 9294, 1752],
 [8416, 8548, 5238, 9737, 1473],
 [8416, 8548, 5238, 9737, 1324],
 [9467, 3318, 167, 9294, 4502],
 [1338, 5430, 8388, 9737]]

In [8]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential  
from tensorflow.keras.utils import pad_sequences

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3318 1828 9294 9976]
 [   0    0    0    0 3318 1828 9294 2642]
 [   0    0    0    0 3318 1219 9294 1752]
 [   0    0    0 8416 8548 5238 9737 1473]
 [   0    0    0 8416 8548 5238 9737 1324]
 [   0    0    0 9467 3318  167 9294 4502]
 [   0    0    0    0 1338 5430 8388 9737]]


In [11]:
## feature representation
dim= 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 268ms/step


array([[[-0.02500019,  0.04420329, -0.03145025,  0.02220566,
          0.03018175, -0.03364968,  0.04924491,  0.01141962,
         -0.00152392, -0.02800559],
        [-0.02500019,  0.04420329, -0.03145025,  0.02220566,
          0.03018175, -0.03364968,  0.04924491,  0.01141962,
         -0.00152392, -0.02800559],
        [-0.02500019,  0.04420329, -0.03145025,  0.02220566,
          0.03018175, -0.03364968,  0.04924491,  0.01141962,
         -0.00152392, -0.02800559],
        [-0.02500019,  0.04420329, -0.03145025,  0.02220566,
          0.03018175, -0.03364968,  0.04924491,  0.01141962,
         -0.00152392, -0.02800559],
        [ 0.03937406,  0.04219594, -0.00240319, -0.02176206,
         -0.01009471,  0.02248433, -0.04520857,  0.00390488,
         -0.03355962,  0.02653743],
        [-0.04046092,  0.04587016,  0.01459238, -0.01532026,
          0.04638768, -0.00538371,  0.01902863,  0.04960969,
         -0.02021695,  0.01889427],
        [-0.00113256, -0.022341  , -0.0267095 ,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 3318, 1828, 9294, 9976])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 80ms/step


array([[-0.02500019,  0.04420329, -0.03145025,  0.02220566,  0.03018175,
        -0.03364968,  0.04924491,  0.01141962, -0.00152392, -0.02800559],
       [-0.02500019,  0.04420329, -0.03145025,  0.02220566,  0.03018175,
        -0.03364968,  0.04924491,  0.01141962, -0.00152392, -0.02800559],
       [-0.02500019,  0.04420329, -0.03145025,  0.02220566,  0.03018175,
        -0.03364968,  0.04924491,  0.01141962, -0.00152392, -0.02800559],
       [-0.02500019,  0.04420329, -0.03145025,  0.02220566,  0.03018175,
        -0.03364968,  0.04924491,  0.01141962, -0.00152392, -0.02800559],
       [ 0.03937406,  0.04219594, -0.00240319, -0.02176206, -0.01009471,
         0.02248433, -0.04520857,  0.00390488, -0.03355962,  0.02653743],
       [-0.04046092,  0.04587016,  0.01459238, -0.01532026,  0.04638768,
        -0.00538371,  0.01902863,  0.04960969, -0.02021695,  0.01889427],
       [-0.00113256, -0.022341  , -0.0267095 ,  0.00239506, -0.00727333,
         0.04183599, -0.03674257,  0.04912524